import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    backgroundColor: 'white',
  },
  closeButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  saveButton: {
    backgroundColor: '#4A62FF',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 60,
    alignItems: 'center',
  },
  saveButtonDisabled: {
    backgroundColor: '#ccc',
  },
  saveButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  saveButtonTextDisabled: {
    color: '#f0f0f0',
  },
  formContainer: {
    flex: 1,
    padding: 20,
  },
  dateText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 15,
  },
  titleInput: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 10,
  },
  emotionsSelector: {
    marginBottom: 20,
  },
  emotionsList: {
    paddingVertical: 5,
  },
  emotionItem: {
    alignItems: 'center',
    marginRight: 15,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  emotionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  emotionLabel: {
    fontSize: 12,
    color: '#666',
  },
  ratingContainer: {
    marginBottom: 20,
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 15,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  sliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  sliderWrapper: {
    flex: 1,
    marginHorizontal: 10,
  },
  slider: {
    height: 40,
  },
  sliderValue: {
    fontSize: 14,
    color: '#666',
    width: 20,
    textAlign: 'center',
  },
  selectedValue: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  premiumContainer: {
    marginBottom: 20,
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 15,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  premiumBadge: {
    position: 'absolute',
    top: -10,
    right: 15,
    backgroundColor: '#FFD700',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 1,
  },
  premiumBadgeText: {
    fontWeight: 'bold',
    fontSize: 12,
    color: '#333',
    marginLeft: 4,
  },
  eventSection: {
    marginBottom: 20,
  },
  eventInput: {
    fontSize: 16,
    color: '#333',
    padding: 10,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  dateButtonText: {
    marginLeft: 8,
    fontSize: 16,
    color: '#333',
  },
  tagsSection: {
    marginBottom: 20,
  },
  tagsInputContainer: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  tagInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    padding: 10,
    backgroundColor: '#f8f9fa',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRightWidth: 0,
  },
  addTagButton: {
    backgroundColor: '#FF5722',
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  suggestedTags: {
    paddingVertical: 10,
  },
  suggestedTag: {
    padding: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FF5722',
    marginRight: 8,
  },
  suggestedTagText: {
    fontSize: 12,
    color: '#FF5722',
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 6,
    paddingHorizontal: 10,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    fontSize: 14,
    marginRight: 6,
  },
  removeTag: {
    padding: 2,
  },
  contentContainer: {
    marginBottom: 20,
  },
  contentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  promptButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e8efff',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  promptButtonText: {
    marginLeft: 5,
    color: '#4A62FF',
    fontWeight: 'bold',
  },
  promptsContainer: {
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  promptItem: {
    paddingVertical: 8,
  },
  promptText: {
    color: '#4A62FF',
  },
  contentInput: {
    fontSize: 16,
    color: '#333',
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    height: 150,
    textAlignVertical: 'top',
  },
  privacyContainer: {
    marginBottom: 20,
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 15,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  privacyOptions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 15,
  },
  privacyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  privacyOptionSelected: {
    borderColor: '#4A62FF',
    backgroundColor: '#e8efff',
  },
  privacyOptionText: {
    marginLeft: 8,
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
  },
  privacyDescription: {
    textAlign: 'center',
    fontSize: 14,
    color: '#666',
  }
});
